/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dados.Dados;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.JogadorDAO;

/**
 *
 * @author willr
 */
public class FrmCadastro extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastro
     */
    public FrmCadastro() {
        initComponents();
        //this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagens/icone-1.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechar = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCancelar = new javax.swing.JLabel();
        lblSalvar = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Five Crowns - Jogo");
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar.fw.png"))); // NOI18N
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFecharMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblFecharMouseReleased(evt);
            }
        });
        getContentPane().add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        txtNome.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        txtNome.setForeground(new java.awt.Color(81, 27, 98));
        txtNome.setBorder(null);
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 344, 320, 40));

        lblCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-cancelar.fw.png"))); // NOI18N
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCancelarMouseReleased(evt);
            }
        });
        getContentPane().add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 170, 60));

        lblSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-salvar.fw.png"))); // NOI18N
        lblSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalvarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblSalvarMouseReleased(evt);
            }
        });
        getContentPane().add(lblSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 170, 60));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-cadastro.fw.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseEntered
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar2.fw.png")));
    }//GEN-LAST:event_lblFecharMouseEntered

    private void lblFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseExited
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar.fw.png")));
    }//GEN-LAST:event_lblFecharMouseExited

    private void lblSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalvarMouseEntered
        lblSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-salvar2.fw.png")));
    }//GEN-LAST:event_lblSalvarMouseEntered

    private void lblSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalvarMouseExited
        lblSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-salvar.fw.png")));
    }//GEN-LAST:event_lblSalvarMouseExited

    private void lblCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseEntered
        lblCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-cancelar2.fw.png")));
    }//GEN-LAST:event_lblCancelarMouseEntered

    private void lblCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseExited
        lblCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-cancelar.fw.png")));
    }//GEN-LAST:event_lblCancelarMouseExited

    private void lblFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseReleased
        dispose();
    }//GEN-LAST:event_lblFecharMouseReleased

    private void lblCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseReleased
        dispose();
    }//GEN-LAST:event_lblCancelarMouseReleased

    private void lblSalvarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalvarMouseReleased
        String nome = txtNome.getText();
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um nome para o jogador!", "Campo obrigatório", 0);
        } else {
            JogadorDAO jDao = new JogadorDAO();
            jDao.inserir(nome);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Sucesso", 1);
            dispose();
        }
    }//GEN-LAST:event_lblSalvarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblSalvar;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
