/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dados.Dados;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.Jogador;

/**
 *
 * @author willr
 */
public class FrmInicial extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicial
     */
    
    private static Point point = new Point();
    
    public FrmInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagens/icone-1.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechar = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        lblIniciar = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Five Crowns");
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar.fw.png"))); // NOI18N
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFecharMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblFecharMouseReleased(evt);
            }
        });
        getContentPane().add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        lblCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-cadastrar.fw.png"))); // NOI18N
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseReleased(evt);
            }
        });
        getContentPane().add(lblCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 355, 340, 60));

        lblIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-iniciar.fw.png"))); // NOI18N
        lblIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIniciarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblIniciarMouseReleased(evt);
            }
        });
        getContentPane().add(lblIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 340, 60));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-inicial.fw.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseEntered
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar2.fw.png")));
    }//GEN-LAST:event_lblFecharMouseEntered

    private void lblFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseExited
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar.fw.png")));
    }//GEN-LAST:event_lblFecharMouseExited

    private void lblCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseEntered
        lblCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-cadastrar2.fw.png")));
    }//GEN-LAST:event_lblCadastrarMouseEntered

    private void lblCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseExited
        lblCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-cadastrar.fw.png")));
    }//GEN-LAST:event_lblCadastrarMouseExited

    private void lblIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarMouseEntered
        lblIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-iniciar2.fw.png")));
    }//GEN-LAST:event_lblIniciarMouseEntered

    private void lblIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarMouseExited
        lblIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-iniciar.fw.png")));
    }//GEN-LAST:event_lblIniciarMouseExited

    private void lblCadastrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseReleased
        FrmCadastro formCadastro = new FrmCadastro();
        formCadastro.setLocationRelativeTo(this);
        formCadastro.setVisible(true);
    }//GEN-LAST:event_lblCadastrarMouseReleased

    private void lblIniciarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarMouseReleased
        if (Dados.listaDeJogadores.size() >= 2) {
            for(Jogador jogador: Dados.listaDeJogadores){
                jogador.setPontos(0);
            }
            Dados.numRodada = 3;
            FrmPartida formPartida = new FrmPartida();
            formPartida.setLocationRelativeTo(this);
            formPartida.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(null, "São necessário pelo menos 2 jogadores cadastrados!", "Número mínimo de jogadores", 0);
        }
    }//GEN-LAST:event_lblIniciarMouseReleased

    private void lblFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseReleased
        dispose();
    }//GEN-LAST:event_lblFecharMouseReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblIniciar;
    // End of variables declaration//GEN-END:variables
}
