/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dados.Dados;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Jogador;
import modelo.JogadorDAO;

/**
 *
 * @author willr
 */
public class FrmPartida extends javax.swing.JFrame {

    /**
     * Creates new form FrmPartida
     */
    public FrmPartida() {
        initComponents();
        //this.setLocationRelativeTo(null);
        jScrollPane.setColumnHeader(null);
        preencheTabela();
        lblNumRodada.setText(Dados.numRodada.toString());
        tblPontuacao.setDefaultRenderer(Object.class, new CellRenderer());
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagens/icone-1.png"));
        return retValue;
    }

    private void preencheTabela() {
        Collections.sort(Dados.listaDeJogadores);
        DefaultTableModel modelo = (DefaultTableModel) tblPontuacao.getModel();
        modelo.setNumRows(0);
        for (Jogador jogador : Dados.listaDeJogadores) {
            modelo.addRow(new Object[]{
                jogador.getId(),
                jogador.getNome(),
                jogador.getPontos()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        tblPontuacao = new javax.swing.JTable();
        lblFechar = new javax.swing.JLabel();
        lblNumRodada = new javax.swing.JLabel();
        lblFinalizar = new javax.swing.JLabel();
        lblRemover = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblAdicionar = new javax.swing.JLabel();
        txtCampo = new javax.swing.JTextField();
        lblCampo = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Five Crowns - Jogo");
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane.setBorder(null);

        tblPontuacao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tblPontuacao.setForeground(new java.awt.Color(81, 27, 98));
        tblPontuacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Pontos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPontuacao.setFocusable(false);
        tblPontuacao.setSelectionBackground(new java.awt.Color(149, 74, 176));
        tblPontuacao.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPontuacao.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(tblPontuacao);
        if (tblPontuacao.getColumnModel().getColumnCount() > 0) {
            tblPontuacao.getColumnModel().getColumn(0).setResizable(false);
            tblPontuacao.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblPontuacao.getColumnModel().getColumn(1).setResizable(false);
            tblPontuacao.getColumnModel().getColumn(2).setResizable(false);
            tblPontuacao.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 155, 342, 112));

        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar.fw.png"))); // NOI18N
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFecharMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblFecharMouseReleased(evt);
            }
        });
        getContentPane().add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        lblNumRodada.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblNumRodada.setForeground(new java.awt.Color(255, 255, 255));
        lblNumRodada.setText("-");
        getContentPane().add(lblNumRodada, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 298, -1, -1));

        lblFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-finalizar.fw.png"))); // NOI18N
        lblFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFinalizarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblFinalizarMouseReleased(evt);
            }
        });
        getContentPane().add(lblFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 320, 70));

        lblRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-remover.fw.png"))); // NOI18N
        lblRemover.setToolTipText("Remover um Jogador");
        lblRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRemoverMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblRemoverMouseReleased(evt);
            }
        });
        getContentPane().add(lblRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 150, 60));

        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-editar.fw.png"))); // NOI18N
        lblEditar.setToolTipText("Editar um Jogador");
        lblEditar.setName(""); // NOI18N
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblEditarMouseReleased(evt);
            }
        });
        getContentPane().add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 150, 60));
        lblEditar.getAccessibleContext().setAccessibleDescription("");

        lblAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-adicionar.fw.png"))); // NOI18N
        lblAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdicionarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAdicionarMouseReleased(evt);
            }
        });
        getContentPane().add(lblAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 230, -1));

        txtCampo.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        txtCampo.setForeground(new java.awt.Color(81, 27, 98));
        txtCampo.setBorder(null);
        getContentPane().add(txtCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 60, 40));

        lblCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/campo-pontos.fw.png"))); // NOI18N
        getContentPane().add(lblCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 350, 90, -1));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-partida.fw.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseEntered
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar2.fw.png")));
    }//GEN-LAST:event_lblFecharMouseEntered

    private void lblFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseExited
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar.fw.png")));
    }//GEN-LAST:event_lblFecharMouseExited

    private void lblFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizarMouseEntered
        lblFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-finalizar2.fw.png")));
    }//GEN-LAST:event_lblFinalizarMouseEntered

    private void lblFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizarMouseExited
        lblFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-finalizar.fw.png")));
    }//GEN-LAST:event_lblFinalizarMouseExited

    private void lblRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoverMouseEntered
        lblRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-remover2.fw.png")));
    }//GEN-LAST:event_lblRemoverMouseEntered

    private void lblRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoverMouseExited
        lblRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-remover.fw.png")));
    }//GEN-LAST:event_lblRemoverMouseExited

    private void lblEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseEntered
        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-editar2.fw.png")));
    }//GEN-LAST:event_lblEditarMouseEntered

    private void lblEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseExited
        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-editar.fw.png")));
    }//GEN-LAST:event_lblEditarMouseExited

    private void lblAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdicionarMouseEntered
        lblAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-adicionar2.fw.png")));
    }//GEN-LAST:event_lblAdicionarMouseEntered

    private void lblAdicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdicionarMouseExited
        lblAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-adicionar.fw.png")));
    }//GEN-LAST:event_lblAdicionarMouseExited

    private void lblFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseReleased
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja sair do jogo?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) {
            dispose();
        }
    }//GEN-LAST:event_lblFecharMouseReleased

    private void lblAdicionarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdicionarMouseReleased

        Integer linha = tblPontuacao.getSelectedRow();
        Integer pontos;
        try {
            pontos = Integer.parseInt(txtCampo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite números no campo de pontos!", "Erro", 0);
            return;
        }

        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um jogador para atribuir pontos!", "Nenhum jogador selecionado", 0);
        } else {
            Integer id = (Integer) tblPontuacao.getValueAt(linha, 0);
            JogadorDAO jDAO = new JogadorDAO();
            Jogador jogador = jDAO.getJogadorPorId(id);
            jogador.setPontos(jogador.getPontos() + pontos);
            preencheTabela();
            txtCampo.setText("");
        }
    }//GEN-LAST:event_lblAdicionarMouseReleased

    private void lblFinalizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizarMouseReleased
        int opcao = JOptionPane.showConfirmDialog(null, "Finalizar rodada " + Dados.numRodada + " ?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) {
            Dados.numRodada++;
            lblNumRodada.setText(Dados.numRodada.toString());
        }
    }//GEN-LAST:event_lblFinalizarMouseReleased

    private void lblRemoverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoverMouseReleased
        Integer linha = tblPontuacao.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Nenhum jogador selecionado!", "Erro", 0);
        } else {
            int opcao = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do jogador?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (opcao == 0) {
                Integer id = (Integer) tblPontuacao.getValueAt(linha, 0);
                JogadorDAO jDAO = new JogadorDAO();
                jDAO.remover(id);
                preencheTabela();
            }
        }
    }//GEN-LAST:event_lblRemoverMouseReleased

    private void lblEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseReleased
        Integer linha = tblPontuacao.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Nenhum jogador selecionado!", "Erro", 0);
        } else {
            Integer id = (Integer) tblPontuacao.getValueAt(linha, 0);
            String nome = (String) tblPontuacao.getValueAt(linha, 1);
            Integer pontos = (Integer) tblPontuacao.getValueAt(linha, 2);
            FrmEditarJogador formEditar = new FrmEditarJogador(id, nome, pontos);
            formEditar.setLocationRelativeTo(this);
            formEditar.setVisible(true);
        }

    }//GEN-LAST:event_lblEditarMouseReleased

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        preencheTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblAdicionar;
    private javax.swing.JLabel lblCampo;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFinalizar;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNumRodada;
    private javax.swing.JLabel lblRemover;
    private javax.swing.JTable tblPontuacao;
    private javax.swing.JTextField txtCampo;
    // End of variables declaration//GEN-END:variables

}
